### ISSUE TITLE
There was a revision in 2022. Just wanna make sure it is accounted for

### ISSUE THREAD

**Issue by mrkvicka22** [deepy/glicko2#3]
![image](https://github.com/deepy/glicko2/assets/40635376/cfb50609-ddd3-4ddf-929a-1b4b73ad78c5)

**Comment by deepy** [comment]
Ah, it does not, I'll fix that directly, I'm currently sick and the dog has emergency surgery so the release will have to wait a few days
Thanks for letting me know about this :-)
